---
title: "RS3_ANOVA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages}
# rm(list = ls())
library(ggplot2)
library(tidyr)
library(dplyr)
library(car) # anova and levenes table
library(apaTables) # for apa tables
library(MBESS) # for apa tables
library(WRS2) # for non-parametric
library(e1071) # for skewness calculation
library(ggpubr) # for interaction plots/boxplots
library(effsize) # for calculating effect sizes
library(compute.es) # ancova using type 3 method
library(multcomp) # post hoc for ancova type 3 method
library(lmPerm)

# example dataframe for stack overflow
# dput(head(modellingdata, n = 5))
```

```{r loading in data}

# home computer working directory
# setwd("C:/Users/Courtney/Documents/PhD/Project/Experiment_code/experiment_1")

# work computer working directory
setwd("C:/Users/pscmgo/OneDrive for Business/PhD/Project/Experiment_Code/teachingcode")
temp = list.files(pattern = c("DataSet_2019", "*.csv")) # list all CSV files in the directory
myfiles = lapply(temp, read.csv) # read these CSV in the directory
workingdata <- do.call(rbind.data.frame, myfiles) # convert and combine the CSV files into dataframe

```

```{r demographics, normality mean scores and reshaping data}

# computing histograms and normality curves for each condition
ggplot(workingdata %>%
         gather("NoAS_Ver", "NoAS_VerDemo", "AS_Ver", "AS_VerDemo", key = "condition", value = "correctpairs"), aes(x = correctpairs)) +
  geom_histogram(aes(y = ..density..)) +
  stat_function(
		fun = dnorm, 
		args = with(workingdata %>%
		              gather("NoAS_Ver", "NoAS_VerDemo", "AS_Ver", "AS_VerDemo", key = "condition", value = "correctpairs"), c(mean = mean(correctpairs), sd = sd(correctpairs)))) + 
  facet_wrap( ~ condition)

# spliting conditions into factors and their levels
split_data <- workingdata %>%
  gather("NoAS_Ver", "NoAS_VerDemo", "AS_Ver", "AS_VerDemo", key = "condition", value = "correctpairs") %>%
  separate(condition, into = c("task", "presentation"))

# age demographics
range(split_data$Age)
mean(split_data$Age)
sd(split_data$Age)

# mean scores for condition
split_data %>%
  group_by(task, presentation) %>%
  summarise(mean_corrected_pairs = mean(correctpairs))

```

Histograms show that data seems fairly normally distributed for each condition. Mean values for each condition show differences. 

```{r checking normality of the data}

# COMPUTE LEVENES TEST HERE #

```

```{r means and anova with table output}

# apa table ANOVA
setwd("C:/Users/pscmgo/OneDrive for Business/PhD/Project/Experiment_Code/teachingcode")
apa.1way.table(condition, correctpairs, workingdata, filename = "RS3_seminar.doc", show.conf.interval = TRUE, landscape = TRUE)

result <- aov(correctpairs ~ condition, data = workingdata)
summary(result)

# Post-hoc tests (only to be used on anova1 type of anova)
resultTukey <-TukeyHSD(result)
resultTukey




```